version: "2"

services:

  web:
    # build: .
    image: ctftraining/delta_2019_web_ssrfme
    restart: always
    ports:
      - "127.0.0.1:8083:5000"
    environment:
      - FLAG=flag{galaxy_want_a_girl_friend}
